export const ADD_POSITION = "ADD_POSITION";
export const REMOVE_POSITION = "REMOVE_POSITION";
export const RESET_BUILDER = "RESET_BUILDER";
export const ADD_PIZZA = "ADD_PIZZA";
export const TO_ORDER = "TO_ORDER";
export const SET_PIZZA = "SET_PIZZA";

export const ADD_TO_CART = "ADD_TO_CART";
export const RESET_CART = "RESET_CART";

export const CHANGE_PIZZA_COUNT = "CHANGE_PIZZA_COUNT";
export const CHANGE_MISC_COUNT = "CHANGE_MISC_COUNT";
export const CHANGE_CONTACTS = "CHANGE_CONTACTS";

export const ADD_TO_ORDERS = "ADD_TO_ORDERS";
export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
