export const ADD_POSITION = "ADD_POSITION";
export const REMOVE_POSITION = "REMOVE_POSITION";
export const RESET_BUILDER = "RESET_BUILDER";
export const ADD_PIZZA = "ADD_PIZZA";
export const TO_ORDER = "TO_ORDER";

export const ADD_TO_CART = "ADD_TO_CART";
export const RESET_CART = "RESET_CART";

export const CHANGE_PIZZA_COUNT = "CHANGE_PIZZA_COUNT";
export const CHANGE_MISC_COUNT = "CHANGE_MISC_COUNT";
export const CHANGE_CONTACTS = "CHANGE_CONTACTS";
